exclude: '^docs/'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: ["--tab-width", "2"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        exclude: hooks/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.288
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  {% if cookiecutter.use_black -%}
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  {%- endif %}

  {% if cookiecutter.use_mypy -%}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "pytest"
          {% if cookiecutter.command_line_interface == "Click" -%}
          - "click"
          {%- endif %}
        args: [ --install-types, --non-interactive]
  {%- endif %}

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
